print("WELCOME!")
print()
story = input("Press any alphabet to Next! ")
print()
print("The Hare and the Tortoise")
print()
story = input("Press any alphabet to Next! ")
print()
print("There was once a hare who was friends with a tortoise.")
print()
story = input("Press any alphabet to Next! ")
print()
print("One day, he challenged the tortoise to a race.")
print()
story = input("Press any alphabet to Next! ")
print()
print("Seeing how slow the tortoise was going, the hare thought he’d win this easily.")
print()
story = input("Press any alphabet to Next! ")
print()
print("So, he took a nap while the tortoise kept on going.")
print()
story = input("Press any alphabet to Next! ")
print()
print("When the hare woke, he saw that the tortoise was already at the finish line.")
print()
story = input("Press any alphabet to Next! ")
print()
print("Much to his chagrin, the tortoise won the race while he was busy sleeping.")
print()
story = input("Press any alphabet to Next! ")
print()
print("THE END")
print()
print("Please write the FEEDBACK for me to improve my programming skill.")
print()
print("TYSM")
quit()

# *NOTES*
# *I'm still Newbie at programming